### ISSUE TITLE
loading data from localstorage is breaking the treeview

### ISSUE THREAD

**Issue by drinovc** [drinovc/eLearning#6]
Figure out why this is not working as expected: 

    // save state to offline storage
    localStorage.setItem('mxp_elearning_slide', Ext.encode(me.getCurrentState()));

    var data = localStorage.getItem('mxp_elearning_slide');
    me.getStore('TreeStoreSlides').setData(data.slides)

**Comment by JernejHabjan** [comment]
This can probably be closed now 😄
